service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

custom:
  apiBaseUrl: https://ayoda6b68a.execute-api.eu-west-1.amazonaws.com/dev
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: npm
  serverless-offline:
    httpPort: 3001

  swagger:
    basePath: /dev
    info:
      title: My API
      version: 1.0.0
    host: https://ayoda6b68a.execute-api.eu-west-1.amazonaws.com/dev

functions:
  getProductsList:
    handler: src/handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductsById:
    handler: src/handler.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
