service: authorization-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  login: kayarmolenka

functions:
  basicAuthorizer:
    handler: src/handler.basicAuthorizer
    environment:
      username: ${self:custom.login}
      password: ${env:${self:custom.login}}